


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."enforce_todo_row_limit"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF (SELECT count(*) FROM public.todos WHERE user_id = NEW.user_id) >= 1000 THEN
        RAISE EXCEPTION 'Maximum limit of 1000 objectives reached per user.';
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."enforce_todo_row_limit"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."calendar" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title" "text",
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."calendar" OWNER TO "postgres";


ALTER TABLE "public"."calendar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."calendar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chore_history" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "chore_id" "uuid" NOT NULL,
    "completed_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."chore_history" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."chores" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "frequency" "text" DEFAULT 'weekly'::"text" NOT NULL,
    "last_completed" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."chores" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."food" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "meal" "text",
    "content" "text",
    "calories" integer,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "is_home_cooked" boolean DEFAULT false
);


ALTER TABLE "public"."food" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."food_inventory" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "item_name" "text" NOT NULL,
    "quantity" "text",
    "unit" "text",
    "category" "text",
    "expiry_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."food_inventory" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."goals" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "target_date" "date",
    "status" "text" DEFAULT 'active'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."goals" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."health" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "metric" "text",
    "value" "text",
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."health" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."health_appointments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "provider" "text" NOT NULL,
    "type" "text",
    "date" "date" NOT NULL,
    "time" time without time zone,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."health_appointments" OWNER TO "postgres";


ALTER TABLE "public"."health" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."health_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ingredients_library" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "last_unit" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."ingredients_library" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "content" "text" NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."meal_plan" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "day_date" "date" NOT NULL,
    "meal_type" "text",
    "recipe_id" "uuid",
    "note" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."meal_plan" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title" "text",
    "amount" numeric,
    "type" "text",
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."money" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money_accounts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "balance" numeric DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money_bills" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "amount" numeric NOT NULL,
    "due_date" "date" NOT NULL,
    "is_paid" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_bills" OWNER TO "postgres";


ALTER TABLE "public"."money" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."money_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."money_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "week_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "amount" numeric DEFAULT 0,
    "is_paid" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money_weeks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "start_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_weeks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "gemini_api_key" "text",
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "feature_hierarchy" "jsonb",
    "page_names" "jsonb",
    "portal_config" "jsonb",
    "dashboard_widgets" "jsonb",
    "theme" "text" DEFAULT 'light'::"text",
    "style" "text" DEFAULT 'default'::"text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON COLUMN "public"."profiles"."feature_hierarchy" IS 'The recursive structure of features and their children.';



COMMENT ON COLUMN "public"."profiles"."page_names" IS 'User-defined names for each feature ID.';



COMMENT ON COLUMN "public"."profiles"."portal_config" IS 'General application settings (showHeaders, autoHideSidebar, etc.).';



COMMENT ON COLUMN "public"."profiles"."dashboard_widgets" IS 'The ordered list of widgets on the dashboard.';



COMMENT ON COLUMN "public"."profiles"."theme" IS 'The user''s dark/light mode preference.';



COMMENT ON COLUMN "public"."profiles"."style" IS 'The user''s visual theme preference (nautical, forest, etc.).';



CREATE TABLE IF NOT EXISTS "public"."reading_list" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "author" "text",
    "status" "text" DEFAULT 'queued'::"text",
    "type" "text" DEFAULT 'book'::"text",
    "rating" integer,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "reading_list_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5)))
);


ALTER TABLE "public"."reading_list" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."recipes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "ingredients" "jsonb" DEFAULT '[]'::"jsonb",
    "instructions" "jsonb" DEFAULT '[]'::"jsonb"
);


ALTER TABLE "public"."recipes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."recreation_camping" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "site_name" "text" NOT NULL,
    "location" "text",
    "start_date" "date",
    "end_date" "date",
    "type" "text" DEFAULT 'tent'::"text",
    "amenities" "text"[],
    "notes" "text",
    "is_favorite" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."recreation_camping" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."recreation_hikes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "location" "text",
    "distance" numeric(5,2),
    "elevation_gain" integer,
    "date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "difficulty" "text" DEFAULT 'moderate'::"text",
    "rating" integer,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "recreation_hikes_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5)))
);


ALTER TABLE "public"."recreation_hikes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."todos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "task" "text",
    "is_complete" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "due_date" "date",
    "status" "text" DEFAULT 'todo'::"text",
    "position" integer DEFAULT 0,
    "description" "text",
    CONSTRAINT "description_length_check" CHECK (("char_length"("description") <= 2000)),
    CONSTRAINT "task_length_check" CHECK (("char_length"("task") <= 500))
);


ALTER TABLE "public"."todos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."travel_bucket_list" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "country" "text",
    "priority" "text" DEFAULT 'medium'::"text",
    "notes" "text",
    "is_visited" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."travel_bucket_list" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."travel_days" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "trip_id" "uuid" NOT NULL,
    "day_number" integer NOT NULL,
    "date" "date",
    "destination_city" "text",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."travel_days" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."travel_packing" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "trip_id" "uuid",
    "item_name" "text" NOT NULL,
    "category" "text" DEFAULT 'general'::"text",
    "is_packed" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."travel_packing" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."travel_poi" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "day_id" "uuid",
    "bucket_id" "uuid",
    "name" "text" NOT NULL,
    "description" "text",
    "location" "text",
    "category" "text" DEFAULT 'other'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "poi_target_check" CHECK (((("day_id" IS NOT NULL) AND ("bucket_id" IS NULL)) OR (("day_id" IS NULL) AND ("bucket_id" IS NOT NULL)) OR (("day_id" IS NULL) AND ("bucket_id" IS NULL))))
);


ALTER TABLE "public"."travel_poi" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."travel_trips" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "status" "text" DEFAULT 'draft'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."travel_trips" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."vault" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "title" "text" NOT NULL,
    "content" "text",
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."vault" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."vehicle_records" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "vehicle_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "date" "date" NOT NULL,
    "odometer" integer,
    "type" "text" DEFAULT 'Maintenance'::"text",
    "description" "text",
    "cost" numeric,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."vehicle_records" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."vehicles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "vin" "text",
    "make" "text",
    "model" "text",
    "year" integer,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "image_url" "text",
    "category" "text" DEFAULT 'car'::"text",
    "style" "text"
);


ALTER TABLE "public"."vehicles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."weather_locations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "latitude" numeric NOT NULL,
    "longitude" numeric NOT NULL,
    "is_primary" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."weather_locations" OWNER TO "postgres";


ALTER TABLE ONLY "public"."calendar"
    ADD CONSTRAINT "calendar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chore_history"
    ADD CONSTRAINT "chore_history_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chores"
    ADD CONSTRAINT "chores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."food_inventory"
    ADD CONSTRAINT "food_inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."food"
    ADD CONSTRAINT "food_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."goals"
    ADD CONSTRAINT "goals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."health_appointments"
    ADD CONSTRAINT "health_appointments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."health"
    ADD CONSTRAINT "health_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ingredients_library"
    ADD CONSTRAINT "ingredients_library_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ingredients_library"
    ADD CONSTRAINT "ingredients_library_user_id_name_key" UNIQUE ("user_id", "name");



ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."meal_plan"
    ADD CONSTRAINT "meal_plan_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_accounts"
    ADD CONSTRAINT "money_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_bills"
    ADD CONSTRAINT "money_bills_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_items"
    ADD CONSTRAINT "money_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money"
    ADD CONSTRAINT "money_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_weeks"
    ADD CONSTRAINT "money_weeks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reading_list"
    ADD CONSTRAINT "reading_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "recipes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recreation_camping"
    ADD CONSTRAINT "recreation_camping_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recreation_hikes"
    ADD CONSTRAINT "recreation_hikes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."travel_bucket_list"
    ADD CONSTRAINT "travel_bucket_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."travel_days"
    ADD CONSTRAINT "travel_days_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."travel_packing"
    ADD CONSTRAINT "travel_packing_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."travel_poi"
    ADD CONSTRAINT "travel_poi_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."travel_trips"
    ADD CONSTRAINT "travel_trips_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vault"
    ADD CONSTRAINT "vault_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vehicle_records"
    ADD CONSTRAINT "vehicle_records_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vehicles"
    ADD CONSTRAINT "vehicles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."weather_locations"
    ADD CONSTRAINT "weather_locations_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "tr_enforce_todo_row_limit" BEFORE INSERT ON "public"."todos" FOR EACH ROW EXECUTE FUNCTION "public"."enforce_todo_row_limit"();



ALTER TABLE ONLY "public"."calendar"
    ADD CONSTRAINT "calendar_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."chore_history"
    ADD CONSTRAINT "chore_history_chore_id_fkey" FOREIGN KEY ("chore_id") REFERENCES "public"."chores"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."chore_history"
    ADD CONSTRAINT "chore_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."chores"
    ADD CONSTRAINT "chores_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."food_inventory"
    ADD CONSTRAINT "food_inventory_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."food"
    ADD CONSTRAINT "food_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."goals"
    ADD CONSTRAINT "goals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."health_appointments"
    ADD CONSTRAINT "health_appointments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."health"
    ADD CONSTRAINT "health_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."ingredients_library"
    ADD CONSTRAINT "ingredients_library_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."meal_plan"
    ADD CONSTRAINT "meal_plan_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."recipes"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."meal_plan"
    ADD CONSTRAINT "meal_plan_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_accounts"
    ADD CONSTRAINT "money_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_bills"
    ADD CONSTRAINT "money_bills_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_items"
    ADD CONSTRAINT "money_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_items"
    ADD CONSTRAINT "money_items_week_id_fkey" FOREIGN KEY ("week_id") REFERENCES "public"."money_weeks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."money"
    ADD CONSTRAINT "money_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_weeks"
    ADD CONSTRAINT "money_weeks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reading_list"
    ADD CONSTRAINT "reading_list_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "recipes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."recreation_camping"
    ADD CONSTRAINT "recreation_camping_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recreation_hikes"
    ADD CONSTRAINT "recreation_hikes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."travel_bucket_list"
    ADD CONSTRAINT "travel_bucket_list_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_days"
    ADD CONSTRAINT "travel_days_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "public"."travel_trips"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_packing"
    ADD CONSTRAINT "travel_packing_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "public"."travel_trips"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_packing"
    ADD CONSTRAINT "travel_packing_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_poi"
    ADD CONSTRAINT "travel_poi_bucket_id_fkey" FOREIGN KEY ("bucket_id") REFERENCES "public"."travel_bucket_list"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_poi"
    ADD CONSTRAINT "travel_poi_day_id_fkey" FOREIGN KEY ("day_id") REFERENCES "public"."travel_days"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_poi"
    ADD CONSTRAINT "travel_poi_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."travel_trips"
    ADD CONSTRAINT "travel_trips_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vault"
    ADD CONSTRAINT "vault_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vehicle_records"
    ADD CONSTRAINT "vehicle_records_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."vehicle_records"
    ADD CONSTRAINT "vehicle_records_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."vehicles"
    ADD CONSTRAINT "vehicles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."weather_locations"
    ADD CONSTRAINT "weather_locations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



CREATE POLICY "Users can insert their own calendar events" ON "public"."calendar" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert their own health logs" ON "public"."health" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert their own money logs" ON "public"."money" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can manage their own POIs" ON "public"."travel_poi" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own accounts" ON "public"."money_accounts" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own appointments" ON "public"."health_appointments" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own bills" ON "public"."money_bills" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own bucket list" ON "public"."travel_bucket_list" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own calendar events" ON "public"."calendar" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own camping trips" ON "public"."recreation_camping" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own chore history" ON "public"."chore_history" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own chores" ON "public"."chores" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own food inventory" ON "public"."food_inventory" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own food records" ON "public"."food" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own goals" ON "public"."goals" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own health records" ON "public"."health" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own hikes" ON "public"."recreation_hikes" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own ingredients library" ON "public"."ingredients_library" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own logs" ON "public"."logs" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own meal plan" ON "public"."meal_plan" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money accounts" ON "public"."money_accounts" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money items" ON "public"."money_items" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money records" ON "public"."money" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money weeks" ON "public"."money_weeks" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own reading list" ON "public"."reading_list" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own recipes" ON "public"."recipes" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own todos" ON "public"."todos" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own travel days" ON "public"."travel_days" USING ((EXISTS ( SELECT 1
   FROM "public"."travel_trips"
  WHERE (("travel_trips"."id" = "travel_days"."trip_id") AND ("travel_trips"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can manage their own travel packing" ON "public"."travel_packing" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own trips" ON "public"."travel_trips" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own vault items" ON "public"."vault" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own vehicle records" ON "public"."vehicle_records" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own vehicles" ON "public"."vehicles" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own weather locations" ON "public"."weather_locations" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own weeks" ON "public"."money_weeks" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see their own calendar events" ON "public"."calendar" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see their own health logs" ON "public"."health" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see their own money logs" ON "public"."money" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update their own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Users can view their own profile." ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



ALTER TABLE "public"."calendar" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chore_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."food" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."food_inventory" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."goals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."health" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."health_appointments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ingredients_library" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."meal_plan" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_bills" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_weeks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reading_list" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recreation_camping" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recreation_hikes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."travel_bucket_list" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."travel_days" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."travel_packing" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."travel_poi" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."travel_trips" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vault" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vehicle_records" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vehicles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."weather_locations" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."enforce_todo_row_limit"() TO "anon";
GRANT ALL ON FUNCTION "public"."enforce_todo_row_limit"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."enforce_todo_row_limit"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";



GRANT ALL ON TABLE "public"."calendar" TO "anon";
GRANT ALL ON TABLE "public"."calendar" TO "authenticated";
GRANT ALL ON TABLE "public"."calendar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."calendar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."calendar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."calendar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chore_history" TO "anon";
GRANT ALL ON TABLE "public"."chore_history" TO "authenticated";
GRANT ALL ON TABLE "public"."chore_history" TO "service_role";



GRANT ALL ON TABLE "public"."chores" TO "anon";
GRANT ALL ON TABLE "public"."chores" TO "authenticated";
GRANT ALL ON TABLE "public"."chores" TO "service_role";



GRANT ALL ON TABLE "public"."food" TO "anon";
GRANT ALL ON TABLE "public"."food" TO "authenticated";
GRANT ALL ON TABLE "public"."food" TO "service_role";



GRANT ALL ON TABLE "public"."food_inventory" TO "anon";
GRANT ALL ON TABLE "public"."food_inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."food_inventory" TO "service_role";



GRANT ALL ON TABLE "public"."goals" TO "anon";
GRANT ALL ON TABLE "public"."goals" TO "authenticated";
GRANT ALL ON TABLE "public"."goals" TO "service_role";



GRANT ALL ON TABLE "public"."health" TO "anon";
GRANT ALL ON TABLE "public"."health" TO "authenticated";
GRANT ALL ON TABLE "public"."health" TO "service_role";



GRANT ALL ON TABLE "public"."health_appointments" TO "anon";
GRANT ALL ON TABLE "public"."health_appointments" TO "authenticated";
GRANT ALL ON TABLE "public"."health_appointments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."health_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."health_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."health_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ingredients_library" TO "anon";
GRANT ALL ON TABLE "public"."ingredients_library" TO "authenticated";
GRANT ALL ON TABLE "public"."ingredients_library" TO "service_role";



GRANT ALL ON TABLE "public"."logs" TO "anon";
GRANT ALL ON TABLE "public"."logs" TO "authenticated";
GRANT ALL ON TABLE "public"."logs" TO "service_role";



GRANT ALL ON TABLE "public"."meal_plan" TO "anon";
GRANT ALL ON TABLE "public"."meal_plan" TO "authenticated";
GRANT ALL ON TABLE "public"."meal_plan" TO "service_role";



GRANT ALL ON TABLE "public"."money" TO "anon";
GRANT ALL ON TABLE "public"."money" TO "authenticated";
GRANT ALL ON TABLE "public"."money" TO "service_role";



GRANT ALL ON TABLE "public"."money_accounts" TO "anon";
GRANT ALL ON TABLE "public"."money_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."money_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."money_bills" TO "anon";
GRANT ALL ON TABLE "public"."money_bills" TO "authenticated";
GRANT ALL ON TABLE "public"."money_bills" TO "service_role";



GRANT ALL ON SEQUENCE "public"."money_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."money_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."money_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."money_items" TO "anon";
GRANT ALL ON TABLE "public"."money_items" TO "authenticated";
GRANT ALL ON TABLE "public"."money_items" TO "service_role";



GRANT ALL ON TABLE "public"."money_weeks" TO "anon";
GRANT ALL ON TABLE "public"."money_weeks" TO "authenticated";
GRANT ALL ON TABLE "public"."money_weeks" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."reading_list" TO "anon";
GRANT ALL ON TABLE "public"."reading_list" TO "authenticated";
GRANT ALL ON TABLE "public"."reading_list" TO "service_role";



GRANT ALL ON TABLE "public"."recipes" TO "anon";
GRANT ALL ON TABLE "public"."recipes" TO "authenticated";
GRANT ALL ON TABLE "public"."recipes" TO "service_role";



GRANT ALL ON TABLE "public"."recreation_camping" TO "anon";
GRANT ALL ON TABLE "public"."recreation_camping" TO "authenticated";
GRANT ALL ON TABLE "public"."recreation_camping" TO "service_role";



GRANT ALL ON TABLE "public"."recreation_hikes" TO "anon";
GRANT ALL ON TABLE "public"."recreation_hikes" TO "authenticated";
GRANT ALL ON TABLE "public"."recreation_hikes" TO "service_role";



GRANT ALL ON TABLE "public"."todos" TO "anon";
GRANT ALL ON TABLE "public"."todos" TO "authenticated";
GRANT ALL ON TABLE "public"."todos" TO "service_role";



GRANT ALL ON TABLE "public"."travel_bucket_list" TO "anon";
GRANT ALL ON TABLE "public"."travel_bucket_list" TO "authenticated";
GRANT ALL ON TABLE "public"."travel_bucket_list" TO "service_role";



GRANT ALL ON TABLE "public"."travel_days" TO "anon";
GRANT ALL ON TABLE "public"."travel_days" TO "authenticated";
GRANT ALL ON TABLE "public"."travel_days" TO "service_role";



GRANT ALL ON TABLE "public"."travel_packing" TO "anon";
GRANT ALL ON TABLE "public"."travel_packing" TO "authenticated";
GRANT ALL ON TABLE "public"."travel_packing" TO "service_role";



GRANT ALL ON TABLE "public"."travel_poi" TO "anon";
GRANT ALL ON TABLE "public"."travel_poi" TO "authenticated";
GRANT ALL ON TABLE "public"."travel_poi" TO "service_role";



GRANT ALL ON TABLE "public"."travel_trips" TO "anon";
GRANT ALL ON TABLE "public"."travel_trips" TO "authenticated";
GRANT ALL ON TABLE "public"."travel_trips" TO "service_role";



GRANT ALL ON TABLE "public"."vault" TO "anon";
GRANT ALL ON TABLE "public"."vault" TO "authenticated";
GRANT ALL ON TABLE "public"."vault" TO "service_role";



GRANT ALL ON TABLE "public"."vehicle_records" TO "anon";
GRANT ALL ON TABLE "public"."vehicle_records" TO "authenticated";
GRANT ALL ON TABLE "public"."vehicle_records" TO "service_role";



GRANT ALL ON TABLE "public"."vehicles" TO "anon";
GRANT ALL ON TABLE "public"."vehicles" TO "authenticated";
GRANT ALL ON TABLE "public"."vehicles" TO "service_role";



GRANT ALL ON TABLE "public"."weather_locations" TO "anon";
GRANT ALL ON TABLE "public"."weather_locations" TO "authenticated";
GRANT ALL ON TABLE "public"."weather_locations" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







