


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."calendar" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title" "text",
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."calendar" OWNER TO "postgres";


ALTER TABLE "public"."calendar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."calendar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."health" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "metric" "text",
    "value" "text",
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."health" OWNER TO "postgres";


ALTER TABLE "public"."health" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."health_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."logs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "content" "text" NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title" "text",
    "amount" numeric,
    "type" "text",
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."money" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money_accounts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "balance" numeric DEFAULT 0,
    "position" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_accounts" OWNER TO "postgres";


ALTER TABLE "public"."money" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."money_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."money_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "week_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "amount" numeric DEFAULT 0,
    "is_paid" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."money_weeks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "start_date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."money_weeks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."todos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "task" "text",
    "is_complete" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."todos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."vault" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "title" "text" NOT NULL,
    "content" "text",
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."vault" OWNER TO "postgres";


ALTER TABLE ONLY "public"."calendar"
    ADD CONSTRAINT "calendar_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."health"
    ADD CONSTRAINT "health_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_accounts"
    ADD CONSTRAINT "money_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_items"
    ADD CONSTRAINT "money_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money"
    ADD CONSTRAINT "money_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."money_weeks"
    ADD CONSTRAINT "money_weeks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vault"
    ADD CONSTRAINT "vault_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."calendar"
    ADD CONSTRAINT "calendar_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."health"
    ADD CONSTRAINT "health_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."money_accounts"
    ADD CONSTRAINT "money_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_items"
    ADD CONSTRAINT "money_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_items"
    ADD CONSTRAINT "money_items_week_id_fkey" FOREIGN KEY ("week_id") REFERENCES "public"."money_weeks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."money"
    ADD CONSTRAINT "money_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."money_weeks"
    ADD CONSTRAINT "money_weeks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."vault"
    ADD CONSTRAINT "vault_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Users can insert their own calendar events" ON "public"."calendar" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert their own health logs" ON "public"."health" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert their own money logs" ON "public"."money" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own accounts" ON "public"."money_accounts" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own calendar events" ON "public"."calendar" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own health records" ON "public"."health" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own logs" ON "public"."logs" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money accounts" ON "public"."money_accounts" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money items" ON "public"."money_items" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money records" ON "public"."money" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own money weeks" ON "public"."money_weeks" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own todos" ON "public"."todos" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own vault items" ON "public"."vault" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own weeks" ON "public"."money_weeks" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see their own calendar events" ON "public"."calendar" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see their own health logs" ON "public"."health" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see their own money logs" ON "public"."money" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."calendar" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."health" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."money_weeks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vault" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."calendar" TO "anon";
GRANT ALL ON TABLE "public"."calendar" TO "authenticated";
GRANT ALL ON TABLE "public"."calendar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."calendar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."calendar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."calendar_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."health" TO "anon";
GRANT ALL ON TABLE "public"."health" TO "authenticated";
GRANT ALL ON TABLE "public"."health" TO "service_role";



GRANT ALL ON SEQUENCE "public"."health_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."health_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."health_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."logs" TO "anon";
GRANT ALL ON TABLE "public"."logs" TO "authenticated";
GRANT ALL ON TABLE "public"."logs" TO "service_role";



GRANT ALL ON TABLE "public"."money" TO "anon";
GRANT ALL ON TABLE "public"."money" TO "authenticated";
GRANT ALL ON TABLE "public"."money" TO "service_role";



GRANT ALL ON TABLE "public"."money_accounts" TO "anon";
GRANT ALL ON TABLE "public"."money_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."money_accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."money_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."money_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."money_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."money_items" TO "anon";
GRANT ALL ON TABLE "public"."money_items" TO "authenticated";
GRANT ALL ON TABLE "public"."money_items" TO "service_role";



GRANT ALL ON TABLE "public"."money_weeks" TO "anon";
GRANT ALL ON TABLE "public"."money_weeks" TO "authenticated";
GRANT ALL ON TABLE "public"."money_weeks" TO "service_role";



GRANT ALL ON TABLE "public"."todos" TO "anon";
GRANT ALL ON TABLE "public"."todos" TO "authenticated";
GRANT ALL ON TABLE "public"."todos" TO "service_role";



GRANT ALL ON TABLE "public"."vault" TO "anon";
GRANT ALL ON TABLE "public"."vault" TO "authenticated";
GRANT ALL ON TABLE "public"."vault" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































drop extension if exists "pg_net";


